# Setup
title:               LMM
tagline:             'Theory & Analysis'
description:         'This page contains material, code, and background on intensive longitudinal data analysis. Made by <a href="https://github.com/lennartseizer" target="_blank">@lennartseizer</a>.'
url:                 'https://lennartseizer.github.io'
baseurl:             '/lmm'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lennart Seizer

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             10/2025
