# Setup
title:               ILD
tagline:             'Theory & Analysis'
description:         'This page contains materials, code, and background on intensive longitudinal data analysis. Made by <a href="https://github.com/lennartseizer" target="_blank">@lennartseizer</a>.'
url:                 'https://lennartseizer.github.io'
baseurl:             '/ild'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Lennart Seizer
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

