name: Knit R Markdown

on:
  push:
    branches:
      - main
    paths:
      - '**/*.Rmd'
  workflow_dispatch:       # ← add this

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: R -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'
      - name: Render
        run: |
          find . -name '*.Rmd' \
            | xargs -I{} Rscript -e "rmarkdown::render('{}', output_format='github_document')"
      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A '*.md' 'figure/*'
          git commit -m "Auto-render Rmd → md [skip ci]" || echo "No changes"
          git push
