# .github/workflows/knit-rmd.yml
name: Knit R Markdown

on:
  push:
    branches:
      - main           # or your default branch
    paths:
      - '**/*.Rmd'     # only runs when an .Rmd changes
  workflow_dispatch:   # allows you to manually trigger it

permissions:
  contents: write      # so the job can push back rendered .md

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        uses: rstudio/actions/setup-pandoc@v2

      - name: Install R dependencies
        run: |
          R -e 'install.packages("rmarkdown", repos="https://cloud.r-project.org")'

      - name: Render all Rmd to Markdown
        run: |
          find . -name '*.Rmd' \
            | xargs -I{} Rscript -e "rmarkdown::render('{}', output_format='github_document')"

      - name: Commit generated Markdown
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all '*.md' 'figure/*'
          git commit -m "Auto-render Rmd → md [skip ci]" || echo "No changes to commit"
          git push
