# .github/workflows/knit-rmd.yml
name: Knit R Markdown
on:
  push:
    paths:
      - '**/*.Rmd'
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown"))'
      - name: Render all Rmd to Markdown
        run: |
          for f in $(find . -name '*.Rmd'); do
            R -e "rmarkdown::render('$f', output_format = 'github_document')"
          done
      - name: Commit generated Markdown
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A '*.md' 'figure/*'
          git commit -m "Auto-render Rmd → md [skip ci]" || echo "No changes to commit"
          git push
